# Generated by Django 5.0.4 on 2024-09-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companymanagement',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='staff_type',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('HR', 'HR'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Company Management', 'Company Management')], max_length=20),
        ),
    ]
