# Generated by Django 5.0.4 on 2024-09-03 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymanagement',
            name='date_of_enquiry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
