# Generated by Django 5.0.4 on 2024-09-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_companymanagement_date_of_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymanagement',
            old_name='date_of_enquiry',
            new_name='date_of_registration',
        ),
    ]
