# Generated by Django 5.0.4 on 2024-09-03 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_employes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employes',
        ),
        migrations.AddField(
            model_name='companymanagement',
            name='staff_members',
            field=models.ManyToManyField(related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.companymanagement'),
        ),
    ]
