# Generated by Django 5.0.4 on 2024-09-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customuser_department_role_customuser_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='complaints',
            field=models.TextField(null=True),
        ),
    ]
