# Generated by Django 5.0.4 on 2024-09-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_customuser_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('hr', 'HR'), ('manager', 'Manager'), ('employee', 'Employee'), ('company management', 'Company Management')], max_length=20),
        ),
    ]
