# Generated by Django 5.0.4 on 2024-09-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_customuser_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department_role',
            field=models.CharField(blank=True, choices=[('finance', 'Finance'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('customer service', 'Customer Service')], max_length=500, null=True),
        ),
    ]
