# Generated by Django 5.0.4 on 2024-09-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_department_alter_customuser_department_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department_role',
            field=models.CharField(blank=True, choices=[('finance', 'Finance'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('customer service', 'Customer Service')], max_length=500, null=True),
        ),
    ]
