# Generated by Django 5.0.4 on 2024-09-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_department_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='departments',
        ),
    ]
