# Generated by Django 5.0.4 on 2024-09-05 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_department_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department'),
        ),
    ]
