# Generated by Django 5.0.4 on 2024-09-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_customuser_department_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='for_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.companymanagement'),
        ),
    ]
