# Generated by Django 5.0.4 on 2024-09-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_department_for_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'for_company')},
        ),
    ]
