# Generated by Django 5.0.4 on 2024-09-06 18:54

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_attendance_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='updated_date',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
