# Generated by Django 5.0.4 on 2024-09-06 18:57

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_attendance_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendence_date',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
