# Generated by Django 5.0.4 on 2024-09-06 19:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_attendance_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
