# Generated by Django 5.0.4 on 2024-09-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_attendance_clock_in_attendance_clock_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='absent',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendence_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
