# Generated by Django 5.0.4 on 2024-09-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='requested_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='responsed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
