# Generated by Django 5.0.4 on 2024-09-07 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_leaverequest_requested_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.department'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='requested_date',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
