# Generated by Django 5.0.4 on 2024-09-07 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_remove_customuser_complaints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='for_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.companymanagement'),
        ),
    ]
